version: '3.3'

services:
  zoo1:
    image: mshapovalov/zookeeper.alpine.3.8.2:latest
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS="server.1=0.0.0.0:2888:3888\n"

   
  kafka1:
    build: .
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      - ZOO_SERVER_CONNECT=zoo1:2181
      - SOCKET_RECEIVE_BYFFER=1456667
      - DELETE_TOPIC=false
      - AUTO_CREATE_TOPIC=false
      - NUM_RECOVERY_THREADS_PER=10
      - REPLIC_FACOTR=2
      - LOG_RETENT_HOURS=10
      - LOG_RETENT_CHECK_INTERVAL_MS=100000
      - NUM_NETWORK=14
      - SOCKET_REQUEST_MAX_B=5555555

 