version: '3.3'

services:
  zoo1:
    image: mshapovalov/zookeeper.alpine.3.8.2:latest
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS="server.1=0.0.0.0:2888:3888\nserver.2=zoo2:2888:3888\nserver.3=zoo3:2888:3888"

  zoo2:
    image: mshapovalov/zookeeper.alpine.3.8.2:latest
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS="server.1=zoo1:2888:3888\nserver.2=0.0.0.0:2888:3888\nserver.3=zoo3:2888:3888"
  
  zoo3:
    image: mshapovalov/zookeeper.alpine.3.8.2:latest
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS="server.1=zoo1:2888:3888\nserver.2=zoo2:2888:3888\nserver.3=0.0.0.0:2888:3888"
  
  kafka1:
    image: mshapovalov/kafka.alpine.cluster:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      - ZOO_SERVER_CONNECT=zoo1:2181,z002:2181,zoo3:2181

  kafka2:
    image: mshapovalov/kafka.alpine.cluster:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9092
    environment:
      - ZOO_SERVER_CONNECT=zoo1:2181,z002:2181,zoo3:2181

  kafka3:
    image: mshapovalov/kafka.alpine.cluster:latest
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9094:9092
    environment:
      - ZOO_SERVER_CONNECT=zoo1:2181,z002:2181,zoo3:2181